const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94720800391"
const SESSION_ID = "PRABATH-MD~dARlgRDY#hGMvNMs4ibsWFZqXmB4b4VXwp0EqSRm-l7USqNuDr0E"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
